### ISSUE TITLE
SPT and Fika version

### ISSUE THREAD

**Issue by ChenMerami** [OnniSaarni/SPT-Fika-Docker-Guide#11]
Maybe you should note that SPT version should be specified for example ARG SPT_BRANCH=3.9.3 (not v3.9.3 as currently shown in your example in installation process) while Fika version should be specified for example ARG FIKA_BRANCH=v2.2.3 (with v)

this argument refers to tags in respective repositories (https://dev.sp-tarkov.com/SPT/Server/src/tag/3.9.3 for SPT and https://github.com/project-fika/Fika-Server/releases/tag/v2.2.3 for Fika)

i got a weird error while building so figured i should let you know 
error was  
    > [builder  9/18] RUN git checkout HEAD^:
    0.288 fatal: not a git repository (or any of the parent directories): .git

**Comment by OnniSaarni** [comment]
Yeah thanks for the issue. This should be fixed now due to this pull request:
https://github.com/OnniSaarni/SPT-Fika-Docker-Guide/pull/10
