### ISSUE TITLE
Can Client use Host Raid Menu in Fika to play with Another Client by using Docker Host as Server?

### ISSUE THREAD

**Issue by karorogunso** [OnniSaarni/SPT-Fika-Docker-Guide#12]
Can Client use Host Raid Menu in Fika to play with Another Client by using Docker Host as Server?

You can check for info here.
https://discord.com/channels/1202292159366037545/1280571507059331243

**Comment by OnniSaarni** [comment]
Yes clients will be able to host raids as long as you're using a vpn or the host has port forwarded the required port. This is more of an issue with setting up a vpn/portforwarding which is kind of unrelated to this guide. The Fika Discord server is good for support with these things but please do let me know if you have any issues with the guide.
