### ISSUE TITLE
a little precision

### ISSUE THREAD

**Issue by cyberbobjr** [OnniSaarni/SPT-Fika-Docker-Guide#2]
don't forget to set your Aki.Server.exe to executable : 

chmod +x Aki.Server.exe

**Comment by OnniSaarni** [comment]
This command in the Dockerfile should do that automatically 

```chmod o+rwx /opt -R```

Did you actually encounter an issue due to this?

**Comment by OnniSaarni** [comment]
I'll probably close this at some point unless anyone has anything to add.

**Comment by OnniSaarni** [comment]
Closing this due to it not being an issue.
