### ISSUE TITLE
Bash Script

### ISSUE THREAD

**Issue by lamduong33** [OnniSaarni/SPT-Fika-Docker-Guide#4]
Not really an issue but would it be helpful to have something like a `start.sh` file that would be able to do all of the necessary steps to automate this whole process?

**Comment by OnniSaarni** [comment]
I was also considering this but I deemed it a bit unnecessary. It's not much work though so I'll probably make a script for this soon. I am not at home for a week so I can't make it yet. If anyone else wants they can make it.

**Comment by OnniSaarni** [comment]
Okay it took a while but I finally got it done 😄 

Made this folder for the script and added it to the table of contents in the main readme.

https://github.com/OnniSaarni/SPT-Fika-Docker-Guide/tree/main/files/setupScript
