### ISSUE TITLE
Potential for Version Mismatches

### ISSUE THREAD

**Issue by pingpongmury** [OnniSaarni/SPT-Fika-Docker-Guide#9]
Hello - The current release of the Fika-Server mod is 2.2.3, while the main branch is 2.2.4. Those who aren't paying attention (like me) can run into issues where the main branch is ahead of releases and it causes issues in-game (players don't spawn together). The Fika Discord helped me track the issue back to my docker install and this version mis-match. I don't know if it's possible for your Dockerfile to pull the latest pre-built releases by default, or maybe just make a note to help prevent absent minded installers like myself from chasing their tails.

I'll take the opportunity here to thank you as well - this made getting my server setup a breeze. Great work!

**Comment by OnniSaarni** [comment]
Thanks for the heads up! There was an issue with this previously but last time the problem was with SPT versions. I don't really have the time to keep updating the version but I'll make sure to add a proper warning for it soon. Thanks!
